repos:
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
    - id: shellcheck
    - id: shfmt
      args: [-i 2]
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.4.0
   hooks:
     - id: check-json
     - id: check-yaml
     - id: check-xml
     - id: pretty-format-json 
